package com.denizcan.moviedatabase.model;

public enum MovieGenre {
    DRAMA,
    ACTION,
    CRIME,
    ROMANCE,
    SCIENCE_FICTION,
    ADVENTURE,
    BIOGRAPHY,
    HISTORY,
    THRILLER,
    DISASTER,
    FANTASY,
    COMEDY,
    HORROR,
    MYSTERY,
    FAMILY,
    WAR,
    WESTERN,
    MUSICAL,
    SPORT,
    CRIME_DRAMA,
    ROMANTIC_COMEDY,
    BIOPIC,
    SUPERHERO,
    NOIR,
    ANIMATION,
    DOCUMENTARY,
    SHORT,
    HISTORICAL,
    POLITICAL,
    ROAD,
    SLICE_OF_LIFE
} 